### ISSUE TITLE
Problem when trying to import McsPyDataTools

### ISSUE THREAD

**Issue by ltallot** [multichannelsystems/McsPyDataTools#1]
After installing McsPyDataTools with pip, which works. I tried to import McsPyDataTools but I get this error message.
I can't find any module named functions_info, I do not know where it's supposed to come from.

Thanks for your help

```
In [5]: import McsPyDataTools
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-e02580c32a7a> in <module>
----> 1 import McsPyDataTools

~\Anaconda3\Scripts\McsPyDataTools.py in <module>
      8 from McsPy import ureg, Q_
      9 #from McsPy.functions_info import print_file_info
---> 10 import functions_info as fi
     11
     12 def show_image_plot(data, aspect_ratio = 10000):

ModuleNotFoundError: No module named 'functions_info'
```

Forgot to add that I am using Python 3 through the Anaconda distribution.

**Comment by armwal** [comment]
Hi, sorry for this (very!) late answer. We had a change in the organization this year, so this project was orphaned for a while until I recently took over as maintainer.

I hope you've figured out the solution for this already, but just in case:

In order to work with the McsPyDataTools package, you'll need to import it by its module name `McsPy`:

```python
import McsPy
import McsPy.McsData
```

The package also contains the (somewhat confusingly named) `McsPyDataTools.py` script which had a bug that led to the error message you observed when `import`ing it. 

We've fixed this bug and several others in the newest toolbox release (V. 0.4.0). We've also improved the documentation, so please check out the Jupyter Notebooks in the `McsPyDataNotebooks` or the tutorials which should be available soon in https://mcspydatatools.readthedocs.io/en/latest/. The version 0.4.0 should get uploaded to PyPi hopefully within the next days.

Again, sorry for answering so late!
