### ISSUE TITLE
OSError: Given HDF5 file contains 'InfoChannel' type of version 2 and supported are only all versions from 1 up to 1

### ISSUE THREAD

**Issue by aeladly91** [multichannelsystems/McsPyDataTools#5]
Hello,

I am trying to read in the recordings I have obtained with the MCS DAQ as a .h5 file into python. I am using the McsPyDataTools package for this. Every time I try to load the raw data in, I keep getting the above error. I think the error is stemming from the __init__.py script in the McsPy folder. 

I  do not know solve this issue. 

Please help.

Thanks

**Comment by armwal** [comment]
Dear Ahmed,

thanks for notifying us! The McsPyDataTools check internally whether the "core" structures in the HDF5 file have the expected versions and otherwise throw the error you are seeing. Very recently, we've updated the `InfoChannel` structure to version 2 in our data acquisition software, but haven't published a compatibility update to the McsPyDataTools, yet. 

I'll do some testing to see whether it will be sufficient to simply allow version 2 of the `InfoChannel` structure in the `init.py` script or if more changes to the code are needed to be compatible to the new `InfoChannel` version.

Best,
Armin

**Comment by aeladly91** [comment]
Amaaaaazing works perfectly. Thank you Armin
